"""
Modern visual theme: curated color palettes (Figma moods plus Places and
Atmosphere, TickTick-style scenic cards), a dynamic "Match
System Appearance" theme, and a fully custom one, font resolution, ttk
styling, and canvas drawing helpers (rounded rects, logo mark,
theme-swatch previews) shared across the app.

Colors are exposed as plain module attributes (theme.PANEL_BG, etc.) so
existing code can keep reading `theme.SOMETHING` without changes. What
switches at runtime is *which* palette those names point at -- call
set_theme("theme_id") to flip them, then re-run apply_theme(root) and
rebuild any plain (non-ttk) widgets so they pick up the new colors (ttk
widgets update automatically via the style engine; raw tk widgets like
Frame/Label/Canvas cache their bg/fg at construction time and need to be
rebuilt -- see MainWindow._apply_theme_and_rebuild).

This used to be a hand-tuned set of seven palettes, each with all ~24
colors picked independently. It's now a larger set -- inspired by
the mood categories (Monochromatic, Romantic, Playful, Vibrant, Neutral,
Tranquil, Seasonal) on Figma's "100 color combinations" resource
(figma.com/resource-library/color-combinations), plus Places and
Atmosphere palettes in the spirit of TickTick's scenic theme cards -- plus "Match System
Appearance", which follows the OS's light/dark setting instead of being
hand-picked, and a "Custom" entry the user builds themselves from a
color picker (see panels.SettingsPanel's custom-color row). Rather than hand-picking all
~24 colors per palette again (error-prone at this count, and the whole
point of a user-driven custom option), every palette -- curated or
custom alike -- is generated by derive_palette() below from just a
handful of seed colors: a background, a panel color, a primary text
color, and an accent. Everything else (borders, muted text, hover/soft
accent tints, grid lines, etc.) is computed from those four using the
same proportional relationships the original seven hand-tuned palettes
actually had (verified by measuring them before writing this).
"""
import math
import subprocess
import sys
import tkinter as tk
import tkinter.font as tkfont
from tkinter import ttk

# ---------------------------------------------------------------------------
# Color math -- small helpers used only to derive a full ~24-color palette
# from a handful of seed colors (see derive_palette below).
# ---------------------------------------------------------------------------
def _hex_to_rgb(hex_color: str):
    h = hex_color.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _rgb_to_hex(rgb) -> str:
    return "#{:02X}{:02X}{:02X}".format(*(max(0, min(255, round(c))) for c in rgb))


def _mix(color_a: str, color_b: str, t: float) -> str:
    """Blend from color_a toward color_b by fraction t (0 = color_a,
    1 = color_b), in plain sRGB. Not perceptually uniform, but plenty
    good enough at the small t values every derived color below uses,
    and it's what the hand-tuned originals turn out to approximate too."""
    a, b = _hex_to_rgb(color_a), _hex_to_rgb(color_b)
    return _rgb_to_hex(a[i] + (b[i] - a[i]) * t for i in range(3))


def _darken(color: str, amount: float) -> str:
    """Multiply each channel toward black by `amount` (0 = unchanged,
    1 = black) -- used for ACCENT_HOVER, a plain darken rather than a mix
    toward some other color."""
    r, g, b = _hex_to_rgb(color)
    factor = 1.0 - amount
    return _rgb_to_hex((r * factor, g * factor, b * factor))


def _is_dark(color: str) -> bool:
    """Perceptual-ish luminance check used only to decide which side of a
    couple of mode-dependent rules (FIELD_BG, SURFACE, default danger/now
    -line colors) a seed palette falls on -- there's no separate light/
    dark toggle the user sets; it's inferred from the panel color itself."""
    r, g, b = _hex_to_rgb(color)
    luminance = 0.299 * r + 0.587 * g + 0.114 * b
    return luminance < 128


# Anti-aliased button images (see rounded_rect_image). Cleared on theme
# change so a leftover PhotoImage can't keep showing yesterday's accent.
_AA_IMAGE_CACHE: dict = {}
_AA_IMAGE_CACHE_MAX = 256


# Dark text used on a bright/light time-block or chart-slice color --
# matches the near-black summary_panel.py's own pie-chart labels already
# used for exactly this problem, reused here rather than inventing a
# second, slightly different near-black.
BLOCK_TEXT_DARK = "#1A1A1A"
BLOCK_TEXT_LIGHT = "#FFFFFF"


def block_text_color(bg_hex: str) -> str:
    """Pick a readable label color for text drawn on top of an arbitrary
    fill color -- calendar_view.py's time-block labels
    (_draw_entry/_update_entry_drag_preview) and summary_panel.py's pie-
    chart slice labels both use this. Unlike ACCENT -- which every
    curated theme picks specifically so plain white text always reads on
    it -- these colors come from whatever a Project was given (one of
    config.DEFAULT_PROJECT_COLORS, or any custom hex the user picked in
    ProjectPanel), independent of the active theme, which spans plenty of
    pale/bright colors white text disappears on. Reuses the same
    luminance check _is_dark() already uses for palette derivation."""
    return BLOCK_TEXT_LIGHT if _is_dark(bg_hex) else BLOCK_TEXT_DARK


def _saturation(color: str) -> float:
    r, g, b = (c / 255.0 for c in _hex_to_rgb(color))
    mx, mn = max(r, g, b), min(r, g, b)
    if mx <= 1e-6:
        return 0.0
    return (mx - mn) / mx


def _desaturate(color: str, amount: float) -> str:
    r, g, b = _hex_to_rgb(color)
    gray = 0.299 * r + 0.587 * g + 0.114 * b
    return _rgb_to_hex((
        r + (gray - r) * amount,
        g + (gray - g) * amount,
        b + (gray - b) * amount,
    ))


def block_fill(color: str, surface: str = None) -> str:
    """The color actually painted for a project on the calendar/sidebar.

    Stored project hexes are often neon (Material defaults, a custom
    picker). Mixing them toward the current surface and pulling saturation
    keeps hue identity while sitting with cream/charcoal chrome.
    """
    raw = (color or "").strip()
    if not raw.startswith("#"):
        raw = ACCENT
    surface = surface or GRID_BG
    sat = _saturation(raw)
    softened = _desaturate(raw, 0.22 * sat)
    toward = 0.16 + 0.30 * sat
    if _is_dark(surface):
        toward *= 0.72
    return _mix(softened, surface, toward)


def calendar_block_fill(color: str, surface: str = None) -> str:
    """Tinted glass over the grid — Apple Calendar, not a pastel sticker.

    Dark chrome keeps a dark wash of the project hue so the block sits
    *in* the UI; light chrome gets a pale wash. Title ink is a separate
    chromatic color (see calendar_block_title_color), the way Reminders
    and Calendar color the label rather than dropping black on mint.
    """
    hue = _project_hex(color)
    surface = surface or GRID_BG
    washed = _desaturate(hue, 0.10)
    if _is_dark(surface):
        return _mix(surface, washed, 0.40)
    return _mix(surface, washed, 0.30)


def calendar_block_title_color(color: str, fill: str = None) -> str:
    """Project hue as the title: lifted on dark tints, deepened on light."""
    hue = _project_hex(color)
    fill = fill or calendar_block_fill(hue)
    if _is_dark(fill):
        lifted = _mix(_desaturate(hue, 0.06), "#FFFFFF", 0.40)
        if _is_dark(lifted):
            lifted = _mix(lifted, "#FFFFFF", 0.40)
        return lifted
    deepened = _mix(hue, BLOCK_TEXT_DARK, 0.22)
    if not _is_dark(deepened):
        deepened = _mix(deepened, BLOCK_TEXT_DARK, 0.35)
    return deepened


def calendar_block_notes_color(color: str, fill: str = None) -> str:
    """Notes recede: same hue as the title, mixed back toward the fill."""
    fill = fill or calendar_block_fill(color)
    title = calendar_block_title_color(color, fill)
    return _mix(title, fill, 0.32)


def calendar_block_rail_color(color: str, fill: str = None) -> str:
    """Left accent on the tinted chip — the saturated identity stripe."""
    hue = _project_hex(color)
    fill = fill or calendar_block_fill(hue)
    if _is_dark(fill):
        return _mix(hue, "#FFFFFF", 0.20)
    return _mix(hue, BLOCK_TEXT_DARK, 0.08)


def unsent_label_color(block_fill: str, project_color: str = None) -> str:
    """Dusty red caption that follows the block's ink, not a Danger pill."""
    if project_color:
        ink = calendar_block_notes_color(project_color, block_fill)
    else:
        ink = block_text_color(block_fill)
    return _mix(DANGER, ink, 0.50)


def _project_hex(color: str) -> str:
    raw = (color or "").strip()
    return raw if raw.startswith("#") else ACCENT


def overlay_fill(surface: str = None) -> str:
    """Wash used for imported calendar meetings -- a guide, not a logged
    block. Mixes the accent toward the grid so it stays visible on light
    and dark themes without competing with real time entries on top."""
    surface = surface or GRID_BG
    return _mix(ACCENT, surface, 0.82)


def overlay_outline(surface: str = None) -> str:
    surface = surface or GRID_BG
    return _mix(ACCENT, surface, 0.62)


def overlay_text_color() -> str:
    return TEXT_MUTED


def derive_palette(app_bg: str, panel_bg: str, text_primary: str, accent: str,
                    danger: str = None, now_line: str = None,
                    accent_b: str = None) -> dict:
    """Build a full ~24-color palette from four required seed colors (an
    app background, a panel/card background, a primary text color, and an
    accent) plus two optional ones (a danger/delete red and a "now" line
    color -- sensible mode-appropriate defaults are used if omitted).

    `accent_b` is an optional second stop for Accent buttons (cyan→violet
    on the Quasar theme). When omitted it matches `accent`, so every
    other palette stays a flat fill.
    """
    dark = _is_dark(panel_bg)
    if danger is None:
        danger = "#E5484D" if dark else "#D6334C"
    if now_line is None:
        now_line = "#FF9500" if dark else "#FF5A36"
    if accent_b is None:
        accent_b = accent

    field_bg = _mix(panel_bg, text_primary, 0.035) if dark else panel_bg
    accent_hover = _darken(accent, 0.17)
    accent_soft = _mix(panel_bg, accent, 0.11)
    accent_mid = accent if accent_b.upper() == accent.upper() else _mix(accent, accent_b, 0.5)

    return {
        "APP_BG": app_bg,
        "PANEL_BG": panel_bg,
        "BORDER": _mix(panel_bg, text_primary, 0.065),
        "BORDER_STRONG": _mix(panel_bg, text_primary, 0.12),
        "TEXT_PRIMARY": text_primary,
        "TEXT_SECONDARY": _mix(text_primary, panel_bg, 0.38),
        "TEXT_MUTED": _mix(text_primary, panel_bg, 0.63),
        "ACCENT": accent,
        "ACCENT_B": accent_b,
        "ACCENT_HOVER": accent_hover,
        "ACCENT_SOFT": accent_soft,
        "DANGER": danger,
        "DANGER_SOFT": _mix(panel_bg, danger, 0.08),
        "DANGER_SOFT_ACTIVE": _mix(panel_bg, danger, 0.16),
        "GRID_LINE": _mix(panel_bg, text_primary, 0.04),
        "GRID_LINE_HOUR": _mix(panel_bg, text_primary, 0.10),
        "HEADER_BG": _mix(panel_bg, text_primary, 0.045),
        "TODAY_TINT": _mix(panel_bg, accent_mid, 0.18) if dark else _mix(panel_bg, accent_mid, 0.12),
        "NOW_LINE": now_line,
        "BLOCK_BORDER": panel_bg,
        "SELECTION_OUTLINE": text_primary,
        "PREVIEW_FILL": accent,
        "PREVIEW_OUTLINE": accent_hover,
        "FIELD_BG": field_bg,
        "SURFACE": field_bg if dark else app_bg,
        "GRID_BG": _mix(panel_bg, text_primary, 0.025) if dark else _mix(app_bg, panel_bg, 0.35),
    }


# White / Dark Mode — the System pair. Auto ("system") reuses these so
# matching the OS always lands on the same two looks as the picker cards.
_WHITE_SEEDS = dict(app_bg="#F2F2F7", panel_bg="#FFFFFF", text_primary="#1C1C1E", accent="#007AFF",
                    danger="#FF3B30", now_line="#FF9500")
_DARK_MODE_SEEDS = dict(app_bg="#000000", panel_bg="#1C1C1E", text_primary="#F5F5F7", accent="#0A84FF",
                        danger="#FF453A", now_line="#FF9F0A")
_SYSTEM_SEEDS_LIGHT = _WHITE_SEEDS
_SYSTEM_SEEDS_DARK = _DARK_MODE_SEEDS

# Rail Delivery Group brand tokens (Pantone 534 / 2965 / 5483 / 7546 /
# 7579 / 158 / 7569). Not a mood palette: navy is the logo, oranges are
# signals. Teal is a supporting cool, not the button colour — using it as
# ACCENT washed the UI into ice-mint and hid the navy.
_RDG_NAVY = "#1C355E"
_RDG_SLATE = "#3D5265"
_RDG_RUST = "#E0592B"
_RDG_ORANGE = "#EE7624"
_RDG_AMBER = "#DB8925"
# Paper tinted with slate (grey-navy), not primary navy — primary has a
# high blue channel and reads as Frozen / pack-ice when diluted.
_RDG_PAPER = _mix("#F7F8FA", _RDG_SLATE, 0.055)
# Night cards sit *on* the logo navy, so they have to lift off it.
_RDG_NIGHT_PANEL = _mix(_RDG_NAVY, "#FFFFFF", 0.14)

# Curated palettes. "category" is the Settings picker section heading;
# THEME_ORDER is the display order, grouped by category.
_PRESETS = [
    ("white", "White", "System",
     "Clean white — the default light look.",
     _WHITE_SEEDS),
    ("dark_mode", "Dark Mode", "System",
     "True dark mode — black chrome, raised cards, same blue accent.",
     _DARK_MODE_SEEDS),

    ("frosted", "Frosted", "Glass",
     "Light rice glass. Use the Translucency slider so the window stays readable.",
     dict(app_bg="#DCE6F0", panel_bg="#F4F8FC", text_primary="#1A2433", accent="#4C8DFF",
          danger="#E5484D", now_line="#FF8A3D")),
    ("picom", "Picom", "Glass",
     "Dark rice glass with a navy accent. Tune Translucency in Settings so text stays sharp.",
     dict(app_bg="#0F1219", panel_bg="#161B24", text_primary="#E8EEF7", accent="#3A6B9A",
          danger="#FF5D7A", now_line="#FFB454")),
    ("hypr", "Hypr", "Glass",
     "Hyprland-night rice — near-black glass and a mauve accent. Tune Translucency below.",
     dict(app_bg="#0B0D14", panel_bg="#12141C", text_primary="#F0EAF8", accent="#CBA6F7",
          danger="#F38BA8", now_line="#FAB387")),

    # Brand — Rail Delivery Group. The logo navy has to appear on chrome
    # (selected tab, Start Timer, Push), not only in body copy. Teal as
    # accent was why RDG Light looked like the Frozen atmosphere theme.
    ("rdg", "RDG", "Brand",
     "Rail Delivery Group — logo navy on buttons and type, slate paper, orange now-line.",
     dict(app_bg=_RDG_PAPER, panel_bg="#FFFFFF", text_primary=_RDG_NAVY, accent=_RDG_NAVY,
          danger=_RDG_RUST, now_line=_RDG_ORANGE)),
    ("rdg_night", "RDG Night", "Brand",
     "RDG after hours — the window is logo navy, cards lift off it, orange for signals.",
     dict(app_bg=_RDG_NAVY, panel_bg=_RDG_NIGHT_PANEL, text_primary="#F3F5F8", accent=_RDG_ORANGE,
          danger=_RDG_RUST, now_line=_RDG_AMBER)),

    ("stormy_morning", "Stormy Morning", "Monochromatic",
     "Charcoal and slate-blue in one family -- calm, restrained, all business.",
     dict(app_bg="#0B0E13", panel_bg="#12161D", text_primary="#EDEFF3", accent="#5B7CA3")),
    ("mossy_hollow", "Mossy Hollow", "Monochromatic",
     "Deep forest green throughout, one quiet hue from background to accent.",
     dict(app_bg="#0A0F0B", panel_bg="#101712", text_primary="#E9F2EA", accent="#4C7A58")),
    ("ink_wash", "Ink Wash", "Monochromatic",
     "Paper white and charcoal ink -- a light monochrome, nothing but gray and near-black.",
     dict(app_bg="#F3F3F4", panel_bg="#FFFFFF", text_primary="#17181C", accent="#3A3D46",
          danger="#C4314B", now_line="#E4572E")),

    ("blooming_romance", "Blooming Romance", "Romantic",
     "Soft blush pink on white -- warm and romantic without tipping into saccharine.",
     dict(app_bg="#FDF4F6", panel_bg="#FFFFFF", text_primary="#3A1420", accent="#D6537B",
          danger="#C0293F", now_line="#E08A2E")),
    ("lavender_fields", "Lavender Fields", "Romantic",
     "Pale lavender and soft violet -- gentle, a little dreamy.",
     dict(app_bg="#F6F3FC", panel_bg="#FFFFFF", text_primary="#2A1F3D", accent="#8B6FD6",
          danger="#D6455E", now_line="#E0932E")),
    ("evening_rose", "Evening Rose", "Romantic",
     "Deep rose on near-black -- the same romantic pink family, after dark.",
     dict(app_bg="#170D12", panel_bg="#21131A", text_primary="#F7E9EE", accent="#E8608A",
          danger="#FF6B6B", now_line="#FFB454")),

    ("zesty_lemon", "Zesty Lemon", "Playful",
     "Bright and citrusy -- a mustard-gold accent on a warm cream background.",
     dict(app_bg="#FDFBEF", panel_bg="#FFFFFF", text_primary="#2B2610", accent="#C99A00",
          danger="#D6334C", now_line="#2F6FED")),
    ("bubblegum_pop", "Bubblegum Pop", "Playful",
     "Hot pink on near-black -- loud, neon, unmistakably playful.",
     dict(app_bg="#0F0A14", panel_bg="#17101F", text_primary="#FBEFFF", accent="#FF4FD8",
          danger="#FF4D6D", now_line="#7CFF6B")),
    ("electric_kiwi", "Electric Kiwi", "Playful",
     "Lime green on near-black -- sharp, energetic, a little irreverent.",
     dict(app_bg="#0A0F08", panel_bg="#10160D", text_primary="#EFFCE9", accent="#84C400",
          danger="#FF5D5D", now_line="#FF9F1C")),

    ("cobalt_rush", "Cobalt Rush", "Vibrant",
     "Electric blue on near-black -- high-contrast and confident.",
     dict(app_bg="#05070F", panel_bg="#0B1020", text_primary="#EAF0FF", accent="#2F6FED",
          danger="#FF3B5C", now_line="#FF9500")),
    ("magenta_pulse", "Magenta Pulse", "Vibrant",
     "Rich magenta on deep violet-black -- vivid and a little electric.",
     dict(app_bg="#0F0714", panel_bg="#180D22", text_primary="#F5EAFB", accent="#C93BE0",
          danger="#FF4D6D", now_line="#FFB454")),
    ("quasar", "Quasar", "Vibrant",
     "Dark slate studio — luminous cyan-to-violet chrome, not a flat fill.",
     dict(app_bg="#0B0E18", panel_bg="#151A28", text_primary="#F4F7FF",
          accent="#2EE6C5", accent_b="#C77DFF",
          danger="#FF6B8A", now_line="#FF6B7A")),

    ("slate_graphite", "Slate Graphite", "Neutral",
     "Cool graphite gray with a muted steel accent -- quiet and professional.",
     dict(app_bg="#0E0F11", panel_bg="#16181B", text_primary="#EDEEF0", accent="#6E7681",
          danger="#E5484D", now_line="#F2994A")),
    ("sandstone", "Sandstone", "Neutral",
     "Warm sand tones with a muted clay accent -- soft daylight neutrality.",
     dict(app_bg="#F5EFE6", panel_bg="#FFFDF9", text_primary="#2E2A22", accent="#B08A5A",
          danger="#C1442E", now_line="#4C7A58")),

    ("ocean_mist", "Ocean Mist", "Tranquil",
     "Pale sea-glass teal on white -- light, airy, easy on the eyes.",
     dict(app_bg="#F0F6F6", panel_bg="#FFFFFF", text_primary="#123435", accent="#2A9D8F",
          danger="#C0293F", now_line="#E76F51")),
    ("sage_retreat", "Sage Retreat", "Tranquil",
     "Soft sage green on white -- calm, natural, unhurried.",
     dict(app_bg="#F3F6F1", panel_bg="#FFFFFF", text_primary="#1F2E1A", accent="#6E9B6B",
          danger="#C1442E", now_line="#D97706")),
    ("midnight_lagoon", "Midnight Lagoon", "Tranquil",
     "Deep teal on near-black -- the same calm sea-glass family, after dark.",
     dict(app_bg="#060F11", panel_bg="#0C1A1D", text_primary="#E4F5F5", accent="#17A6A0",
          danger="#FF5D5D", now_line="#FFB454")),

    ("autumn_harvest", "Autumn Harvest", "Seasonal",
     "Toasted brown and burnt orange -- a cozy, low-light autumn palette.",
     dict(app_bg="#140D08", panel_bg="#1F140C", text_primary="#FBEEE1", accent="#E08A2E",
          danger="#C1442E", now_line="#7CA84C")),
    ("winter_frost", "Winter Frost", "Seasonal",
     "Icy pale blue on white -- crisp, clean, a little wintry.",
     dict(app_bg="#F2F7FB", panel_bg="#FFFFFF", text_primary="#142433", accent="#4E7CB8",
          danger="#C0293F", now_line="#E0932E")),

    # Places — city/region moods (TickTick-style scenic cards; original palettes).
    ("cairo_sun", "Cairo", "Places",
     "Warm desert sand and terracotta — late afternoon over the dunes.",
     dict(app_bg="#F4E4CC", panel_bg="#FFF8EE", text_primary="#3A2414", accent="#E07A32",
          danger="#C1442E", now_line="#2A7A8C")),
    ("thames_fog", "London", "Places",
     "Cool fog and river grey, with a bus-red accent.",
     dict(app_bg="#E6EBF1", panel_bg="#FFFFFF", text_primary="#1C2430", accent="#C8102E",
          danger="#9B1B2E", now_line="#E08A2E")),
    ("pacific_drive", "Los Angeles", "Places",
     "Peach sunset, palm-teal water, highway-hour light.",
     dict(app_bg="#FFE6D2", panel_bg="#FFF6EE", text_primary="#2A1810", accent="#FF6B45",
          danger="#D6334C", now_line="#2A9D8F")),
    ("winter_square", "Moscow", "Places",
     "Icy blue snow and a deep winter red.",
     dict(app_bg="#E4EEF6", panel_bg="#FFFFFF", text_primary="#1A2744", accent="#C41E3A",
          danger="#9B1830", now_line="#E08A2E")),
    ("harbor_dusk", "New York", "Places",
     "Dusk navy skyline with a warm gold window-light accent.",
     dict(app_bg="#14182C", panel_bg="#1C2238", text_primary="#EEF1FF", accent="#E8A317",
          danger="#FF5D5D", now_line="#FF8A3D")),
    ("bay_span", "San Francisco", "Places",
     "Bay fog and International Orange — the colour of the bridge.",
     dict(app_bg="#E8EEF2", panel_bg="#FFFFFF", text_primary="#1E2A32", accent="#C4501A",
          danger="#C0293F", now_line="#2A7A8C")),
    ("han_spring", "Seoul", "Places",
     "Temple red and spring green on warm paper.",
     dict(app_bg="#F3F0E8", panel_bg="#FFFCF6", text_primary="#2C2418", accent="#C45C4A",
          danger="#B03030", now_line="#6E9B6B")),
    ("pearl_night", "Shanghai", "Places",
     "River-city night: deep indigo and neon violet.",
     dict(app_bg="#0B1024", panel_bg="#151A34", text_primary="#E8ECFF", accent="#7B5CFF",
          danger="#FF4D6D", now_line="#FFB454")),
    ("opera_bay", "Sydney", "Places",
     "Harbour blue and a coral sunset on white sails.",
     dict(app_bg="#DFF0F6", panel_bg="#FFFFFF", text_primary="#0E2A38", accent="#E07A4A",
          danger="#C0293F", now_line="#1D7A8C")),
    ("fuji_night", "Tokyo", "Places",
     "Night indigo and sakura pink — city lights under the mountain.",
     dict(app_bg="#12101C", panel_bg="#1A1828", text_primary="#F7EEF4", accent="#E89AB5",
          danger="#FF6B6B", now_line="#7CFFD0")),

    # Atmosphere — photograph moods, same idea as TickTick's photo themes.
    ("cut_stone", "Architecture", "Atmosphere",
     "Limestone and shadow — quiet galleries and concrete.",
     dict(app_bg="#EBE6DE", panel_bg="#FAF7F2", text_primary="#2C2824", accent="#8A7A68",
          danger="#C1442E", now_line="#4C7A58")),
    ("silver_grain", "B&W", "Atmosphere",
     "Silver gelatin — no colour, just light and grain.",
     dict(app_bg="#141414", panel_bg="#1E1E1E", text_primary="#F2F2F2", accent="#A8A8A8",
          danger="#E5484D", now_line="#FFFFFF")),
    ("dune_heat", "Desert", "Atmosphere",
     "Hot sand and a high-noon ochre sun.",
     dict(app_bg="#F3E0B8", panel_bg="#FFF6E4", text_primary="#3D2A14", accent="#D4A017",
          danger="#C1442E", now_line="#2A7A8C")),
    ("deep_canopy", "Greenery", "Atmosphere",
     "Leaf-filtered light — moss, fern, and shade.",
     dict(app_bg="#E5F0E2", panel_bg="#F7FBF5", text_primary="#1A2E18", accent="#3D7A45",
          danger="#C1442E", now_line="#D97706")),
    ("swallow_sky", "Swallow", "Atmosphere",
     "Open sky and a swallow-blue horizon.",
     dict(app_bg="#D4E8F6", panel_bg="#F4FAFD", text_primary="#1A3040", accent="#3D7FA8",
          danger="#C0293F", now_line="#E08A2E")),
    ("first_light", "Dawn", "Atmosphere",
     "First light — peach sky before the day starts.",
     dict(app_bg="#FFDCC8", panel_bg="#FFF4EC", text_primary="#3A2018", accent="#E07048",
          danger="#C0293F", now_line="#4E7CB8")),
    ("orchard_bloom", "Blossom", "Atmosphere",
     "Petal pink and orchard light.",
     dict(app_bg="#FBE8EE", panel_bg="#FFF7F9", text_primary="#3A1828", accent="#E07090",
          danger="#C0293F", now_line="#E08A2E")),
    ("pack_ice", "Frozen", "Atmosphere",
     "Pack ice and a polar-blue horizon.",
     dict(app_bg="#E4F2F8", panel_bg="#F7FCFE", text_primary="#143044", accent="#4A96B8",
          danger="#C0293F", now_line="#E08A2E")),
]

THEMES = {
    theme_id: {
        "label": label,
        "description": description,
        "category": category,
        "palette": derive_palette(**seeds),
    }
    for theme_id, label, category, description, seeds in _PRESETS
}

CUSTOM_THEME_ID = "custom"

# Like "custom", "system" (Auto) isn't a fixed entry in THEMES -- it
# follows the OS light/dark setting and reuses the White / Dark Mode
# palettes. White and Dark Mode themselves are normal curated ids.
SYSTEM_THEME_ID = "system"
WHITE_THEME_ID = "white"
DARK_MODE_THEME_ID = "dark_mode"

# Display order: White and Dark Mode first (the System pair), then Auto
# (follows the OS into those same two palettes), then the rest of the
# curated ids grouped by category. "custom" is NOT in here -- it's
# appended separately wherever the picker is drawn.
THEME_ORDER = [WHITE_THEME_ID, DARK_MODE_THEME_ID, SYSTEM_THEME_ID] + [
    theme_id for theme_id, *_ in _PRESETS
    if theme_id not in (WHITE_THEME_ID, DARK_MODE_THEME_ID)
]

DEFAULT_THEME_ID = SYSTEM_THEME_ID

# Anyone upgrading from the old seven-palette system (or the light/dark
# toggle before that) gets mapped onto the closest match among the new
# twenty rather than losing their preference outright.
_LEGACY_MODE_MAP = {
    "light": "white", "dark": "dark_mode",
    "sleek_indigo": "stormy_morning", "neon_cyan": "cobalt_rush",
    "crisp_light": "white", "emerald_terminal": "mossy_hollow",
    "warm_amber": "sandstone", "violet_nebula": "magenta_pulse",
    "mac_glass": "ocean_mist",
}

# The user's own Custom palette -- four seed colors (background, panel,
# text, accent), defaulting to Cobalt Rush's until they pick their own via
# panels.SettingsPanel's color pickers. Persisted separately (see
# get_custom_seeds/set_custom_seeds and main_window.py's startup load) so
# it survives restarts even when "custom" isn't the active theme.
_custom_seeds = dict(app_bg="#05070F", panel_bg="#0B1020", text_primary="#EAF0FF", accent="#2F6FED")


def get_custom_seeds() -> dict:
    return dict(_custom_seeds)


def set_custom_seeds(app_bg: str, panel_bg: str, text_primary: str, accent: str):
    """Update the Custom palette's seed colors. Safe to call freely while
    the user is still picking colors in Settings (see
    panels.SettingsPanel) -- it only changes what the "custom" theme id
    resolves to; it doesn't touch whichever palette is actually active
    until/unless set_theme("custom") is called too."""
    _custom_seeds.update(app_bg=app_bg, panel_bg=panel_bg, text_primary=text_primary, accent=accent)


# Auto ("system") reuses _WHITE_SEEDS / _DARK_MODE_SEEDS above.

_system_is_dark_cache = None


def _detect_system_is_dark() -> bool:
    """Best-effort, once-per-run check of the OS's current light/dark
    appearance setting, cached after the first call -- this is checked
    only at startup, not polled live, so if the user flips their OS
    appearance while the app is open the "Match System Appearance" theme
    won't follow until the app is restarted. Falls back to dark (this
    app's own long-standing default look) on any unsupported platform or
    failed check -- a themed-wrong app beats one that crashes on
    startup."""
    global _system_is_dark_cache
    if _system_is_dark_cache is not None:
        return _system_is_dark_cache
    is_dark = True
    if sys.platform == "darwin":
        try:
            result = subprocess.run(
                ["defaults", "read", "-g", "AppleInterfaceStyle"],
                capture_output=True, text=True, timeout=2,
            )
            # macOS only *sets* this key when Dark mode is active -- a
            # missing key (non-zero exit, empty stdout) means Light mode.
            is_dark = result.returncode == 0 and result.stdout.strip().lower() == "dark"
        except Exception:
            pass
    elif sys.platform == "win32":
        try:
            import winreg
            key = winreg.OpenKey(
                winreg.HKEY_CURRENT_USER,
                r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize",
            )
            value, _ = winreg.QueryValueEx(key, "AppsUseLightTheme")
            is_dark = value == 0
        except Exception:
            pass
    _system_is_dark_cache = is_dark
    return is_dark


def get_theme(theme_id: str) -> dict:
    """Look up a theme's {label, description, palette} by id, including
    the special "custom" id -- which isn't a fixed entry in THEMES, but is
    built live from whatever set_custom_seeds() last stored, so it always
    reflects the user's current picks even before they've hit Save."""
    theme_id = resolve_theme_id(theme_id)
    if theme_id == CUSTOM_THEME_ID:
        return {
            "label": "Custom",
            "category": "Custom",
            "description": "Your own palette -- pick a background, panel, text, and accent "
                            "color below and the rest is filled in to match.",
            "palette": derive_palette(**_custom_seeds),
        }
    if theme_id == SYSTEM_THEME_ID:
        seeds = _SYSTEM_SEEDS_DARK if _detect_system_is_dark() else _SYSTEM_SEEDS_LIGHT
        return {
            "label": "Auto",
            "category": "System",
            "description": "Follows your Mac or Windows light/dark setting — "
                            "White or Dark Mode. Checked once when the app starts; "
                            "switching your OS appearance while the app is open won't "
                            "change it until you restart.",
            "palette": derive_palette(**seeds),
        }
    return THEMES[theme_id]


def resolve_theme_id(value) -> str:
    """Turn a stored settings value (a current theme id, a legacy "light"/
    "dark" mode string or old palette id, or anything else/missing) into
    a valid theme id -- one of the twenty curated ids or "custom"."""
    if value == CUSTOM_THEME_ID or value == SYSTEM_THEME_ID or value in THEMES:
        return value
    if value in _LEGACY_MODE_MAP:
        return _LEGACY_MODE_MAP[value]
    return DEFAULT_THEME_ID


CURRENT_THEME_ID = DEFAULT_THEME_ID

# Explicit module-level bindings for every palette key (rather than only
# setting them dynamically inside set_theme()) so static analysis sees real
# top-level names -- `theme.PANEL_BG` etc. -- instead of attributes that
# only exist at runtime. set_theme() below reassigns each of these via an
# explicit `global` statement, which keeps both static analysis and the
# runtime dynamic-repaint behavior working.
_DEFAULT_PALETTE = get_theme(DEFAULT_THEME_ID)["palette"]
APP_BG: str = _DEFAULT_PALETTE["APP_BG"]
PANEL_BG: str = _DEFAULT_PALETTE["PANEL_BG"]
BORDER: str = _DEFAULT_PALETTE["BORDER"]
BORDER_STRONG: str = _DEFAULT_PALETTE["BORDER_STRONG"]
TEXT_PRIMARY: str = _DEFAULT_PALETTE["TEXT_PRIMARY"]
TEXT_SECONDARY: str = _DEFAULT_PALETTE["TEXT_SECONDARY"]
TEXT_MUTED: str = _DEFAULT_PALETTE["TEXT_MUTED"]
ACCENT: str = _DEFAULT_PALETTE["ACCENT"]
ACCENT_B: str = _DEFAULT_PALETTE.get("ACCENT_B", ACCENT)
# Extra pixels around luminous Accent buttons (Quasar's cyan→violet glow).
ACCENT_GLOW_PAD = 8
ACCENT_HOVER: str = _DEFAULT_PALETTE["ACCENT_HOVER"]
ACCENT_SOFT: str = _DEFAULT_PALETTE["ACCENT_SOFT"]
DANGER: str = _DEFAULT_PALETTE["DANGER"]
DANGER_SOFT: str = _DEFAULT_PALETTE["DANGER_SOFT"]
DANGER_SOFT_ACTIVE: str = _DEFAULT_PALETTE["DANGER_SOFT_ACTIVE"]
GRID_LINE: str = _DEFAULT_PALETTE["GRID_LINE"]
GRID_LINE_HOUR: str = _DEFAULT_PALETTE["GRID_LINE_HOUR"]
HEADER_BG: str = _DEFAULT_PALETTE["HEADER_BG"]
TODAY_TINT: str = _DEFAULT_PALETTE["TODAY_TINT"]
NOW_LINE: str = _DEFAULT_PALETTE["NOW_LINE"]
BLOCK_BORDER: str = _DEFAULT_PALETTE["BLOCK_BORDER"]
SELECTION_OUTLINE: str = _DEFAULT_PALETTE["SELECTION_OUTLINE"]
PREVIEW_FILL: str = _DEFAULT_PALETTE["PREVIEW_FILL"]
PREVIEW_OUTLINE: str = _DEFAULT_PALETTE["PREVIEW_OUTLINE"]
FIELD_BG: str = _DEFAULT_PALETTE["FIELD_BG"]
SURFACE: str = _DEFAULT_PALETTE["SURFACE"]
GRID_BG: str = _DEFAULT_PALETTE["GRID_BG"]


def set_theme(theme_id: str):
    """Point every color constant in this module at the given theme id
    (one of THEMES, or "custom" -- see get_theme above). Falls back to
    the default / maps legacy light-dark values via resolve_theme_id() on
    anything else."""
    global CURRENT_THEME_ID, APP_BG, PANEL_BG, BORDER, BORDER_STRONG, TEXT_PRIMARY, \
        TEXT_SECONDARY, TEXT_MUTED, ACCENT, ACCENT_B, ACCENT_HOVER, ACCENT_SOFT, DANGER, DANGER_SOFT, \
        DANGER_SOFT_ACTIVE, GRID_LINE, GRID_LINE_HOUR, HEADER_BG, TODAY_TINT, NOW_LINE, \
        BLOCK_BORDER, SELECTION_OUTLINE, PREVIEW_FILL, PREVIEW_OUTLINE, FIELD_BG, SURFACE, GRID_BG

    theme_id = resolve_theme_id(theme_id)
    _AA_IMAGE_CACHE.clear()
    CURRENT_THEME_ID = theme_id
    p = get_theme(theme_id)["palette"]

    APP_BG = p["APP_BG"]
    PANEL_BG = p["PANEL_BG"]
    BORDER = p["BORDER"]
    BORDER_STRONG = p["BORDER_STRONG"]
    TEXT_PRIMARY = p["TEXT_PRIMARY"]
    TEXT_SECONDARY = p["TEXT_SECONDARY"]
    TEXT_MUTED = p["TEXT_MUTED"]
    ACCENT = p["ACCENT"]
    ACCENT_B = p.get("ACCENT_B") or p["ACCENT"]
    ACCENT_HOVER = p["ACCENT_HOVER"]
    ACCENT_SOFT = p["ACCENT_SOFT"]
    DANGER = p["DANGER"]
    DANGER_SOFT = p["DANGER_SOFT"]
    DANGER_SOFT_ACTIVE = p["DANGER_SOFT_ACTIVE"]
    GRID_LINE = p["GRID_LINE"]
    GRID_LINE_HOUR = p["GRID_LINE_HOUR"]
    HEADER_BG = p["HEADER_BG"]
    TODAY_TINT = p["TODAY_TINT"]
    NOW_LINE = p["NOW_LINE"]
    BLOCK_BORDER = p["BLOCK_BORDER"]
    SELECTION_OUTLINE = p["SELECTION_OUTLINE"]
    PREVIEW_FILL = p["PREVIEW_FILL"]
    PREVIEW_OUTLINE = p["PREVIEW_OUTLINE"]
    FIELD_BG = p["FIELD_BG"]
    SURFACE = p["SURFACE"]
    GRID_BG = p["GRID_BG"]


def darken(color: str, amount: float) -> str:
    """Public wrapper around the palette helper -- calendar time-blocks use
    this for a slightly deeper left edge so they read as raised chips
    rather than flat stamps."""
    return _darken(color, amount)


def get_theme_id() -> str:
    return CURRENT_THEME_ID


def theme_label(theme_id: str) -> str:
    return get_theme(theme_id)["label"]


# Populate the module-level constants immediately so `theme.PANEL_BG` etc.
# work for any code that imports this module before a Database/settings
# lookup has a chance to call set_theme() with the user's saved preference.
set_theme(DEFAULT_THEME_ID)

_FONT_FAMILY = None


def resolve_font_family(root=None) -> str:
    """Pick the best-looking sans-serif font available on this machine.

    Must be called after a Tk root exists (tkfont.families() needs one).
    Cached after the first call.
    """
    global _FONT_FAMILY
    if _FONT_FAMILY is not None:
        return _FONT_FAMILY
    preferred = ["Segoe UI", "SF Pro Text", "Helvetica Neue", "Helvetica",
                 "Ubuntu", "Cantarell", "Noto Sans", "Arial", "DejaVu Sans"]
    try:
        available = set(tkfont.families(root))
    except Exception:
        available = set()
    for name in preferred:
        if name in available:
            _FONT_FAMILY = name
            break
    else:
        _FONT_FAMILY = "TkDefaultFont"
    return _FONT_FAMILY


def font(root=None, size=10, weight="normal"):
    return (resolve_font_family(root), size, weight)


def apply_theme(root):
    """Configure global widget defaults + ttk styles for the whole app,
    using whatever palette set_theme() last selected. Safe to call again
    after switching themes -- ttk widgets re-render immediately since ttk
    styles are looked up dynamically; plain tk widgets do not and must be
    rebuilt separately (see MainWindow._apply_theme_and_rebuild)."""
    family = resolve_font_family(root)

    root.configure(bg=APP_BG)
    # Sets the default font for every classic Tk widget (Label, Button,
    # Text, Listbox, Menu, ...) app-wide in one shot.
    root.option_add("*Font", (family, 10))
    root.option_add("*Menu.background", PANEL_BG)
    root.option_add("*Menu.foreground", TEXT_PRIMARY)
    root.option_add("*Menu.activeBackground", ACCENT_SOFT)
    root.option_add("*Menu.activeForeground", ACCENT)
    root.option_add("*Menu.borderWidth", 1)

    # A ttk.Combobox's dropdown list is a plain classic-Tk Listbox under the
    # hood, which does NOT pick up ttk styling -- left alone it renders with
    # Tk's own default colors (typically black-on-white) regardless of
    # theme, which stands out as an unreadable/jarring flash against a dark
    # panel. Themed explicitly here so every dropdown (Activity, Day,
    # Start/End time, Theme picker, etc.) matches whichever theme is active.
    root.option_add("*TCombobox*Listbox.background", FIELD_BG)
    root.option_add("*TCombobox*Listbox.foreground", TEXT_PRIMARY)
    root.option_add("*TCombobox*Listbox.selectBackground", ACCENT)
    root.option_add("*TCombobox*Listbox.selectForeground", "#FFFFFF")

    style = ttk.Style(root)
    try:
        style.theme_use("clam")
    except Exception:
        pass

    style.configure("TFrame", background=PANEL_BG)
    style.configure("App.TFrame", background=APP_BG)
    style.configure("Card.TFrame", background=PANEL_BG)

    style.configure("TLabel", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 10))
    style.configure("Secondary.TLabel", background=PANEL_BG, foreground=TEXT_SECONDARY, font=(family, 9))
    style.configure("Heading.TLabel", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 18, "bold"))

    # Primary (accent) button
    style.configure("Accent.TButton", background=ACCENT, foreground="white",
                     font=(family, 10, "bold"), padding=(14, 8), borderwidth=0, relief="flat")
    style.map("Accent.TButton",
              background=[("active", ACCENT_HOVER), ("pressed", ACCENT_HOVER)],
              foreground=[("disabled", TEXT_MUTED)])

    # Secondary (neutral) button. Idle fill is SURFACE, not APP_BG -- APP_BG
    # is the app's own base/outermost layer, darker than the PANEL_BG these
    # buttons actually sit on in every dark theme, which made them read as a
    # dim, sunken notch instead of a button. SURFACE is deliberately a step
    # *lighter* than PANEL_BG in dark themes (mirroring how BORDER/
    # BORDER_STRONG already correctly lighten further on hover/press) while
    # keeping the original APP_BG look for light themes, where a slightly
    # darker idle fill reads fine. See widgets._BUTTON_STYLES for the actual
    # hand-drawn RoundedButton this app renders (this ttk style is now
    # unused directly but kept in sync so it isn't a stale trap later).
    style.configure("Secondary.TButton", background=SURFACE, foreground=TEXT_PRIMARY,
                     font=(family, 10), padding=(10, 6), borderwidth=0, relief="flat")
    style.map("Secondary.TButton", background=[("active", BORDER), ("pressed", BORDER_STRONG)])

    # Small nav (‹ Today ›) buttons -- same reasoning as Secondary above:
    # hover should get more prominent than idle, which means lighter (not
    # darker) once the surrounding panel is itself dark.
    style.configure("Nav.TButton", background=PANEL_BG, foreground=TEXT_PRIMARY,
                     font=(family, 10), padding=(8, 5), borderwidth=1, relief="flat")
    style.map("Nav.TButton", background=[("active", SURFACE)], bordercolor=[("!disabled", BORDER_STRONG)])

    style.configure("Danger.TButton", background=DANGER_SOFT, foreground=DANGER,
                     font=(family, 10), padding=(10, 6), borderwidth=0, relief="flat")
    style.map("Danger.TButton", background=[("active", DANGER_SOFT_ACTIVE)])

    style.configure("TEntry", fieldbackground=FIELD_BG, foreground=TEXT_PRIMARY, padding=6,
                     borderwidth=1, relief="flat", bordercolor=BORDER_STRONG,
                     insertcolor=TEXT_PRIMARY)
    style.configure("TCombobox", fieldbackground=FIELD_BG, background=FIELD_BG, foreground=TEXT_PRIMARY,
                     padding=6, borderwidth=1, relief="flat", arrowsize=14)
    style.map("TCombobox", fieldbackground=[("readonly", FIELD_BG)],
              selectbackground=[("readonly", FIELD_BG)], selectforeground=[("readonly", TEXT_PRIMARY)],
              foreground=[("readonly", TEXT_PRIMARY)])

    style.configure("Big.TLabel", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 12))
    style.configure("Big.TEntry", fieldbackground=FIELD_BG, foreground=TEXT_PRIMARY, padding=10,
                     borderwidth=1, relief="flat", bordercolor=BORDER_STRONG,
                     insertcolor=TEXT_PRIMARY, font=(family, 12))
    style.configure("Big.TCombobox", fieldbackground=FIELD_BG, background=FIELD_BG, foreground=TEXT_PRIMARY,
                     padding=10, borderwidth=1, relief="flat", arrowsize=16, font=(family, 12))
    style.map("Big.TCombobox", fieldbackground=[("readonly", FIELD_BG)],
              selectbackground=[("readonly", FIELD_BG)], selectforeground=[("readonly", TEXT_PRIMARY)],
              foreground=[("readonly", TEXT_PRIMARY)])
    style.configure("Big.TCheckbutton", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 12))

    style.configure("TRadiobutton", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 10))
    style.configure("TCheckbutton", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 10))
    # The "clam" base theme's own Checkbutton/Radiobutton style swaps in a
    # bright default background the moment the mouse is over it (its
    # built-in "active" state color, never overridden above) -- jarring
    # against a themed, often-dark panel. Pinning "active" back to the
    # same PANEL_BG as everything else removes that flash entirely rather
    # than just picking a softer replacement color.
    style.map("TCheckbutton", background=[("active", PANEL_BG)])
    style.map("Big.TCheckbutton", background=[("active", PANEL_BG)])
    style.map("TRadiobutton", background=[("active", PANEL_BG)])

    # Tab bar: ttk.Notebook's own native tab strip is square-cornered with
    # no way to round it short of per-theme 9-slice image assets (this app
    # has none, deliberately -- see requirements.txt) or replacing it with
    # hand-drawn RoundedButton toggles the way MainWindow._build_body does
    # (its own tab_bar row, driving this same notebook via .select()).
    #
    # -tabposition is a real ttk::notebook option, but only settable on the
    # widget instance itself (self.notebook.configure(tabposition=...)) --
    # style.configure() silently accepts and stores an option name it
    # doesn't recognize without raising, so an earlier attempt to hide the
    # native strip this way did nothing and just left both tab rows
    # showing at once ("duplicate tabs"). Emptying "TNotebook.Tab"'s own
    # element layout is the real, widely-used fix: with no elements to
    # draw, every native tab collapses to zero size, while every other
    # Notebook mechanic (.add/.tab/.select, hidden-vs-normal panel state,
    # <<NotebookTabChanged>>) keeps working underneath exactly as before --
    # none of that lives in the Tab element's layout.
    style.configure(
        "TNotebook",
        background=APP_BG,
        borderwidth=0,
        relief="flat",
        padding=0,
        lightcolor=APP_BG,
        darkcolor=APP_BG,
        bordercolor=APP_BG,
    )
    style.configure("TNotebook.Pane", background=APP_BG, borderwidth=0)
    style.layout("TNotebook.Tab", [])
    # clam's Notebook.client still draws a 3D square around the page even
    # with borderwidth=0; painting those edges in APP_BG hides the box.
    try:
        style.layout("TNotebook", [("Notebook.client", {"sticky": "nswe"})])
    except tk.TclError:
        pass

    apply_window_chrome(root)
    apply_window_opacity(root)
    return family


# macOS traffic lights sit in the top-left of a full-size content view
# (TickTick / VS Code "hidden inset" titlebar). Content must pad past them.
MAC_TRAFFIC_INSET_PX = 70
MAC_TITLEBAR_PX = 28


def apply_window_chrome(root):
    """Paint the native macOS titlebar with the theme instead of system white.

    Uses Tk's Aqua -stylemask fullsizecontentview (transparent titlebar,
    content drawn underneath) plus -appearance so the traffic lights match
    light/dark palettes. Other platforms keep the stock window frame.
    """
    root._themed_titlebar = False
    if sys.platform != "darwin":
        return
    try:
        root.wm_attributes("-appearance", "darkaqua" if _is_dark(APP_BG) else "aqua")
    except tk.TclError:
        try:
            root.tk.call(
                "::tk::unsupported::MacWindowStyle", "appearance",
                root._w, "darkaqua" if _is_dark(APP_BG) else "aqua")
        except tk.TclError:
            pass
    try:
        root.wm_attributes(
            "-stylemask",
            "titled closable miniaturizable resizable fullsizecontentview",
        )
        root._themed_titlebar = True
        # Native title draws in the same strip as our header; hide it so
        # the logo + name only appear once (traffic lights stay).
        try:
            root.title("")
        except tk.TclError:
            pass
    except tk.TclError:
        return


# Glass / rice themes drop the whole window's opacity so the desktop
# shows through (Tk has no per-widget blur). 1.0 = opaque. Linux needs a
# compositor (Picom, Hyprland, KWin) for this to be visible.
#
# The user-chosen value is shared across Frosted / Picom / Hypr so a
# slider in Settings can keep text readable. Floor is high enough that
# labels don't wash out.
GLASS_THEME_IDS = frozenset({"frosted", "picom", "hypr"})
WINDOW_ALPHA_MIN = 0.88
WINDOW_ALPHA_MAX = 1.0
WINDOW_ALPHA_DEFAULT = 0.95
_glass_alpha = WINDOW_ALPHA_DEFAULT


def is_glass_theme(theme_id: str = None) -> bool:
    tid = resolve_theme_id(theme_id if theme_id is not None else CURRENT_THEME_ID)
    return tid in GLASS_THEME_IDS


def accent_is_luminous() -> bool:
    """True when Accent buttons should bloom (cyan→violet), not sit flat."""
    extra = ACCENT_B or ACCENT
    return str(extra).upper() != str(ACCENT).upper()


def clamp_glass_alpha(value) -> float:
    try:
        alpha = float(value)
    except (TypeError, ValueError):
        alpha = WINDOW_ALPHA_DEFAULT
    return max(WINDOW_ALPHA_MIN, min(WINDOW_ALPHA_MAX, alpha))


def get_glass_alpha() -> float:
    return _glass_alpha


def set_glass_alpha(value) -> float:
    global _glass_alpha
    _glass_alpha = clamp_glass_alpha(value)
    return _glass_alpha


def window_alpha(theme_id: str = None) -> float:
    tid = resolve_theme_id(theme_id if theme_id is not None else CURRENT_THEME_ID)
    if tid not in GLASS_THEME_IDS:
        return 1.0
    return _glass_alpha


def apply_window_opacity(root, theme_id: str = None):
    """Set wm -alpha for Glass themes; restore full opacity otherwise."""
    alpha = window_alpha(theme_id)
    try:
        root.wm_attributes("-alpha", alpha)
    except tk.TclError:
        try:
            root.attributes("-alpha", alpha)
        except tk.TclError:
            pass


def themed_titlebar_left_pad() -> int:
    """Extra left inset so header text clears the macOS traffic lights."""
    return MAC_TRAFFIC_INSET_PX if sys.platform == "darwin" else 0


# ---------------------------------------------------------------------------
# Canvas drawing helpers
# ---------------------------------------------------------------------------
def _ring_points(cx, cy, rx, ry, rot_deg, start_deg=0, end_deg=360, steps=None):
    """Sample points along a (possibly partial) ellipse centered at
    (cx, cy) and rotated by rot_deg -- used to build every tilted ring/arc
    in draw_logo_mark below. Tkinter's create_oval/create_arc only draw
    axis-aligned shapes, so a tilted one has to be built as a plain point
    list fed to create_line instead; like rounded_rect() above, this
    samples real trigonometric points rather than using
    create_line(..., smooth=True), which approximates a spline *near* its
    control points rather than through them (see rounded_rect's docstring
    for the visible artifacts that caused, on a Retina display in
    particular).

    Unlike rounded_rect's angle convention (0=east/90=north, with y
    flipped to compensate for the canvas's y-down coordinate space), this
    works entirely in plain screen/canvas coordinates with no flip, and
    angles/rotation match SVG's rotate() transform directly. That's
    because this mark's proportions were designed and approved as an SVG
    mockup first -- porting those numbers verbatim was the lower-risk way
    to reproduce the design exactly, rather than translating them into a
    different convention by hand.

    Returns a flat [x1, y1, x2, y2, ...] list, ready for
    canvas.create_line(*points, ...)."""
    if steps is None:
        steps = max(8, round(abs(end_deg - start_deg) / 5))
    rot = math.radians(rot_deg)
    cos_r, sin_r = math.cos(rot), math.sin(rot)
    points = []
    for i in range(steps + 1):
        theta = math.radians(start_deg + (end_deg - start_deg) * i / steps)
        x0 = rx * math.cos(theta)
        y0 = ry * math.sin(theta)
        points.append(cx + x0 * cos_r - y0 * sin_r)
        points.append(cy + x0 * sin_r + y0 * cos_r)
    return points


def draw_logo_mark(canvas, size=28, pad=1):
    """Draw the QUASAR mark: a clock-faced core sphere wrapped in a
    tilted, Saturn-style ring system with a bright shooting-star taper on
    its near edge, plus a scattering of small stars. Deliberately not an
    emoji or symbol-font glyph, since those aren't reliably available on
    every machine (headless/minimal Linux installs in particular).

    Tkinter has no native support for rotated ellipses, real alpha
    blending, or blur, so every tilted ring/arc here is a point-sampled
    line (see _ring_points above) and every "opacity" from the original
    design is faked with a solid color pre-blended toward whatever
    actually sits behind that shape -- the canvas's own background for
    anything drawn on empty space, or ACCENT for anything drawn over the
    opaque sphere -- via the _mix() helper near the top of this module.
    packaging/make_icons.py draws the same design again independently,
    using Pillow's real compositing and rotation for the packaged app
    icon; the two aren't shared code, so a future redesign needs both
    updated.

    Uses the module's live ACCENT (not a fixed color), so this header
    mark re-themes along with everything else when the user picks a
    different theme; make_icons.py's packaged icon stays a fixed brand
    blue instead, since that one can't change after the app is built."""
    canvas.delete("all")
    scale = (size - 2 * pad) / 120.0
    bg = PANEL_BG  # this canvas's own background -- see main_window.py's construction

    def X(x):
        return pad + x * scale

    def Y(y):
        return pad + y * scale

    def W(width):
        return max(1.0, width * scale)

    def line(points, **kwargs):
        canvas.create_line(*(X(p) if i % 2 == 0 else Y(p) for i, p in enumerate(points)), **kwargs)

    def polygon(points, **kwargs):
        canvas.create_polygon(*(X(p) if i % 2 == 0 else Y(p) for i, p in enumerate(points)), **kwargs)

    # ---- Saturn-style ring system (back pass, behind the sphere) -------
    ring_cx, ring_cy, ring_rot = 60, 66, -20
    line(_ring_points(ring_cx, ring_cy, 60, 11, ring_rot),
         fill=_mix(bg, ACCENT, 0.28), width=W(2), dash=(2, 5))
    line(_ring_points(ring_cx, ring_cy, 54, 9.5, ring_rot),
         fill=_mix(bg, ACCENT, 0.42), width=W(2.5))
    line(_ring_points(ring_cx, ring_cy, 48, 8, ring_rot),
         fill=_mix(bg, ACCENT, 0.5), width=W(5), capstyle="round")

    # ---- core sphere -----------------------------------------------------
    sx, sy, r = 60, 50, 25
    canvas.create_oval(X(sx - r), Y(sy - r), X(sx + r), Y(sy + r), fill=ACCENT, outline="")

    # ---- watch-face bezel: semi-transparent white over the sphere -------
    br = 19.5
    canvas.create_oval(X(sx - br), Y(sy - br), X(sx + br), Y(sy + br),
                        outline=_mix(ACCENT, "#FFFFFF", 0.3), width=W(1.5))

    # ---- clock hands, fixed at 10:10 (the classic "friendly" clock
    # position) -- the timesheet reference the halo design was missing.
    canvas.create_line(X(sx), Y(sy), X(52.6), Y(44.8), fill="white", width=W(3.6), capstyle="round")
    canvas.create_line(X(sx), Y(sy), X(72.1), Y(43), fill="white", width=W(3.6), capstyle="round")
    cr = 2.4
    canvas.create_oval(X(sx - cr), Y(sy - cr), X(sx + cr), Y(sy + cr), fill="white", outline="")

    # ---- the ring's front/near edge, tapering from dim to a bright
    # near-white point like a shooting star -- three nested partial arcs
    # sharing the same start angle, each shorter and brighter than the
    # last, each pre-blended against ACCENT (what they're actually drawn
    # over) instead of the canvas background.
    line(_ring_points(ring_cx, ring_cy, 48, 8, ring_rot, 20, 160),
         fill=_mix(ACCENT, "#6EA0FF", 0.55), width=W(4), capstyle="round")
    line(_ring_points(ring_cx, ring_cy, 48, 8, ring_rot, 20, 100),
         fill=_mix(ACCENT, "#B7D0FF", 0.8), width=W(3.5), capstyle="round")
    line(_ring_points(ring_cx, ring_cy, 48, 8, ring_rot, 20, 60),
         fill="#F3F8FF", width=W(3), capstyle="round")

    # ---- a scattered handful of stars for the "in space" feel -- each
    # sits on empty background, so blended toward `bg` rather than ACCENT.
    def sparkle(cx, cy, long_r, short_r, alpha):
        k = short_r * 0.70710678  # short_r at 45 degrees
        polygon([cx, cy - long_r, cx + k, cy - k, cx + long_r, cy,
                 cx + k, cy + k, cx, cy + long_r, cx - k, cy + k,
                 cx - long_r, cy, cx - k, cy - k],
                fill=_mix(bg, "#FFFFFF", alpha), outline="")

    sparkle(100, 18, 6, 2, 0.9)
    sparkle(14, 24, 3, 1, 0.55)
    sparkle(10, 100, 3.5, 1.2, 0.6)
    dot_r = 1.8
    canvas.create_oval(X(108 - dot_r), Y(102 - dot_r), X(108 + dot_r), Y(102 + dot_r),
                        fill=_mix(bg, "#FFFFFF", 0.5), outline="")


def draw_theme_swatch(canvas, theme_id: str, selected: bool, width=132, height=88):
    """Draw a small live preview card for one theme onto `canvas`, using
    that theme's own palette directly (not the app's currently-active
    globals above) -- this is what lets Settings show every preset side by
    side regardless of which one is actually active right now. Works for
    "custom" exactly like any other id -- get_theme() builds its palette
    live from the user's current seed colors either way.

    Places and Atmosphere cards get a tiny scenic illustration (sky, sun,
    skyline) so the picker reads like TickTick's theme grid. Other palettes
    keep the miniature calendar: an inset panel and two time-block bars.
    """
    canvas.delete("all")
    info = get_theme(theme_id)
    p = info["palette"]
    category = info.get("category") or ""

    place_rounded_rect(canvas, 1, 1, width - 1, height - 1, radius=10,
                       fill=p["APP_BG"], outline="", background=p["APP_BG"])

    if category in ("Places", "Atmosphere", "Glass"):
        _draw_scenic_mini(canvas, p, theme_id, width, height)
    else:
        card_pad = 10
        card_top = 10
        place_rounded_rect(canvas, card_pad, card_top, width - card_pad, height - 12,
                           radius=6, fill=p["PANEL_BG"], outline=p["BORDER"], width=1,
                           background=p["APP_BG"])
        bar_x = card_pad + 8
        bar_w = width - 2 * (card_pad + 8)
        place_rounded_rect(canvas, bar_x, card_top + 12, bar_x + bar_w, card_top + 26,
                           radius=3, fill=p["ACCENT"], outline="", background=p["PANEL_BG"])
        place_rounded_rect(canvas, bar_x, card_top + 32, bar_x + bar_w * 0.62, card_top + 46,
                           radius=3, fill=p["BORDER_STRONG"], outline="", background=p["PANEL_BG"])

    outline_color = p["ACCENT"] if selected else p["BORDER_STRONG"]
    outline_width = 3 if selected else 1
    rounded_rect(canvas, 1, 1, width - 1, height - 1, radius=10, outline=outline_color,
                 width=outline_width, fill="")

    if selected:
        badge_r = 9
        bx, by = width - 14, 14
        canvas.create_oval(bx - badge_r, by - badge_r, bx + badge_r, by + badge_r,
                            fill=p["ACCENT"], outline="")
        canvas.create_line(bx - 4, by, bx - 1, by + 3, bx + 4, by - 4,
                            fill="white", width=2, capstyle="round", joinstyle="round")


def _draw_scenic_mini(canvas, p, theme_id: str, width: int, height: int):
    """Tiny sky / sun / skyline using only this palette's colors."""
    sky = p["APP_BG"]
    ground = p["PANEL_BG"]
    accent = p["ACCENT"]
    dark = _is_dark(p["PANEL_BG"])
    horizon = int(height * 0.58)

    canvas.create_rectangle(6, 6, width - 6, horizon, fill=sky, outline="")
    canvas.create_rectangle(6, horizon, width - 6, height - 6, fill=ground, outline="")

    seed = sum(ord(c) for c in theme_id)
    sr = 9 + (seed % 5)
    sx = width - 22 - (seed % 18)
    sy = 18 + (seed % 10)
    canvas.create_oval(sx - sr, sy - sr, sx + sr, sy + sr, fill=accent, outline="")

    if dark:
        for i in range(5):
            dx = 12 + ((seed * (i + 3)) % (width - 40))
            dy = 12 + ((seed * (i + 7)) % 22)
            canvas.create_oval(dx, dy, dx + 2, dy + 2, fill=p["TEXT_MUTED"], outline="")

    n = 5 + (seed % 3)
    x = 8
    gap = 2
    avail = width - 16 - gap * (n - 1)
    bw = max(8, avail // n)
    for i in range(n):
        bh = 10 + ((seed * (i + 5) * 13) % 26)
        x0 = x + i * (bw + gap)
        canvas.create_rectangle(x0, horizon - bh, x0 + bw, horizon + 2,
                                fill=_mix(ground, accent, 0.22 if i % 2 else 0.08),
                                outline="")
    canvas.create_polygon(
        6, horizon + 6,
        18 + (seed % 20), horizon - 8,
        40 + (seed % 30), horizon + 4,
        width - 6, horizon + 8,
        width - 6, height - 6,
        6, height - 6,
        fill=_mix(ground, p["TEXT_PRIMARY"], 0.06), outline="")


def rounded_rect(canvas, x1, y1, x2, y2, radius: float = 8, exponent: float = 4.0, **kwargs):
    """Draw a rounded rectangle on `canvas`, as a single polygon item.

    This has gone through two worse designs before landing here, both
    visible as real "artifacts" reported on real hardware (a Retina
    MacBook) that a plain-DPI Linux test environment never surfaced:

    1. Originally a single `create_polygon(..., smooth=True)` -- Tk's
       polygon smoothing approximates a spline *near* its control points
       rather than through them, which could leave a sliver of the
       canvas's flat background color poking out right at a corner.
    2. Then rewritten as several composited items per shape (quarter-circle
       "pieslice" arcs for the fill, plain arc outlines for the border,
       plus rectangles/lines for the straight edges) to get true circular
       corners. That fixed (1) but traded it for a worse, platform-specific
       problem: Tk's `create_arc` outline rendering (particularly with a
       thicker `width`, as the Settings theme-picker's selected-swatch ring
       uses) can draw past the arc's own bounding box at the start/end caps
       on some Tk builds -- visible as a small square notch poking out at
       a corner, exactly where the previous approach left a gap instead.

    This version samples real trigonometric points around each corner's
    true circular arc (no spline approximation) and draws the WHOLE shape
    -- all four corners and the straight edges between them -- as one
    `create_polygon` call, which natively supports fill AND outline
    together. One item means no seam between separately-drawn pieces is
    possible, and no per-item arc/line stroke-cap quirks either.

    `exponent` controls the corner *curve family*, not just its radius.
    2.0 is a true circular arc (the original design). Apple's "continuous
    corner" / squircle rounding used throughout iOS and macOS is smoother
    than a circular arc -- it keeps curving into the straight edge instead
    of meeting it at an abrupt tangent point -- and is commonly approximated
    with a superellipse of degree ~4-5. This defaults to 4.0 so every
    rounded shape in the app (buttons, cards, the calendar's own corners)
    reads as "Apple-style" without every call site needing to opt in.

    Returns the created item id (useful for the one caller --
    calendar_view._draw_entry -- that stacks its label text via
    `tag_raise(text_item, this_return_value)`).
    """
    x1, x2 = (x1, x2) if x1 <= x2 else (x2, x1)
    y1, y2 = (y1, y2) if y1 <= y2 else (y2, y1)
    radius = max(0.0, min(radius, (x2 - x1) / 2, (y2 - y1) / 2))

    if radius <= 0:
        return canvas.create_rectangle(x1, y1, x2, y2, **kwargs)

    points = rounded_rect_points(x1, y1, x2, y2, radius=radius, exponent=exponent)
    return canvas.create_polygon(points, **kwargs)


def rounded_rect_points(x1, y1, x2, y2, radius: float = 8, exponent: float = 4.0,
                        steps=None):
    """Flat [x, y, ...] list for a superellipse rounded rect.

    Live calendar previews reuse the same point count every motion
    (`steps` fixed) so `canvas.coords` can reshape the polygon without
    recreating it — a PhotoImage per mouse-pixel would hitch, and a
    plain `create_rectangle` looks stair-stepped on Retina.
    """
    x1, x2 = (x1, x2) if x1 <= x2 else (x2, x1)
    y1, y2 = (y1, y2) if y1 <= y2 else (y2, y1)
    radius = max(0.0, min(float(radius), (x2 - x1) / 2, (y2 - y1) / 2))
    if radius <= 0:
        return [x1, y1, x2, y1, x2, y2, x1, y2]
    corners = [
        (x2 - radius, y1 + radius, 90, 0),
        (x2 - radius, y2 - radius, 0, -90),
        (x1 + radius, y2 - radius, -90, -180),
        (x1 + radius, y1 + radius, -180, -270),
    ]
    if steps is None:
        steps = max(18, int(radius * 2.5))
    steps = max(4, int(steps))
    power = 2.0 / exponent
    points = []
    for cx, cy, start_deg, end_deg in corners:
        for i in range(steps + 1):
            deg = start_deg + (end_deg - start_deg) * i / steps
            rad = math.radians(deg)
            cos_v = math.cos(rad)
            sin_v = math.sin(rad)
            points.append(cx + radius * math.copysign(abs(cos_v) ** power, cos_v))
            points.append(cy - radius * math.copysign(abs(sin_v) ** power, sin_v))
    return points


def _sdf_rounded_rect(px: float, py: float, x1: float, y1: float,
                      x2: float, y2: float, radius: float) -> float:
    """Signed distance to a rounded rectangle (negative = inside)."""
    cx = (x1 + x2) * 0.5
    cy = (y1 + y2) * 0.5
    half_w = (x2 - x1) * 0.5
    half_h = (y2 - y1) * 0.5
    dx = abs(px - cx) - (half_w - radius)
    dy = abs(py - cy) - (half_h - radius)
    ox = dx if dx > 0.0 else 0.0
    oy = dy if dy > 0.0 else 0.0
    inside = dx if dx > dy else dy
    if inside > 0.0:
        inside = 0.0
    return math.hypot(ox, oy) + inside - radius


def _coverage(distance: float) -> float:
    """Smoothstep across ~2 logical pixels.

    PhotoImages are 1 Tk-pixel and get doubled on Retina, so a 1px
    coverage ramp becomes a 2px stair. A wider smoothstep stays round
    after that blit.
    """
    width = 2.0
    t = 0.5 - distance / width
    if t <= 0.0:
        return 0.0
    if t >= 1.0:
        return 1.0
    return t * t * (3.0 - 2.0 * t)


def _average_hex(colors) -> str:
    n = len(colors) or 1
    acc = [0, 0, 0]
    for color in colors:
        rgb = _hex_to_rgb(color)
        acc[0] += rgb[0]
        acc[1] += rgb[1]
        acc[2] += rgb[2]
    return _rgb_to_hex((acc[0] / n, acc[1] / n, acc[2] / n))


def _aa_pixel(px: float, py: float, box, radius: float, fill: str,
              background: str, outline: str, stroke: float) -> str:
    x1, y1, x2, y2 = box
    outer = _sdf_rounded_rect(px, py, x1, y1, x2, y2, radius)
    if stroke > 0.0 and outline:
        inner_r = max(0.0, radius - stroke)
        inner = _sdf_rounded_rect(
            px, py, x1 + stroke, y1 + stroke, x2 - stroke, y2 - stroke, inner_r)
        a_outer = _coverage(outer)
        if a_outer <= 0.0:
            return background
        color = outline if a_outer >= 1.0 else _mix(background, outline, a_outer)
        a_inner = _coverage(inner)
        if a_inner <= 0.0:
            return color
        return fill if a_inner >= 1.0 else _mix(color, fill, a_inner)
    a = _coverage(outer)
    if a <= 0.0:
        return background
    if a >= 1.0:
        return fill
    return _mix(background, fill, a)


def _make_aa_image(width: int, height: int, radius: float, fill: str,
                   background: str, outline: str, stroke: float, box=None,
                   backgrounds=None, fill_end: str = "", glow: float = 0.0):
    import tkinter as tk

    width = max(1, int(width))
    height = max(1, int(height))
    fill = (fill or "#000000").upper()
    background = (background or "#000000").upper()
    outline = (outline or "").upper()
    fill_end = (fill_end or "").upper()
    if fill_end == fill:
        fill_end = ""
    glow = max(0.0, float(glow or 0.0))
    if box is None:
        if glow > 0.0:
            box = (glow + 0.5, glow + 0.5, width - glow - 0.5, height - glow - 0.5)
        else:
            box = (0.5, 0.5, width - 0.5, height - 0.5)
    if backgrounds is None:
        nw = ne = sw = se = background
        uniform = True
    else:
        nw, ne, sw, se = [
            (c or background or "#000000").upper() for c in backgrounds]
        uniform = nw == ne == sw == se
        if uniform:
            background = nw
    key = (width, height, round(float(radius), 2), fill, fill_end,
           (nw, ne, sw, se) if not uniform else background, outline,
           round(float(stroke), 2), tuple(round(v, 2) for v in box),
           round(glow, 2))
    cached = _AA_IMAGE_CACHE.get(key)
    if cached is not None:
        return cached
    span = max(width - 1, 1)

    def fill_at(px):
        if not fill_end:
            return fill
        t = max(0.0, min(1.0, (px - 0.5) / span))
        return _mix(fill, fill_end, t)

    rows = []
    def sample(px, py, bg=background):
        def one(sx, sy):
            pix_fill = fill_at(sx)
            dist = _sdf_rounded_rect(sx, sy, box[0], box[1], box[2], box[3], radius)
            if stroke > 0.0 and outline and glow <= 0.0:
                return _aa_pixel(sx, sy, box, radius, pix_fill, bg, outline, stroke)
            a = _coverage(dist)
            glow_a = 0.0
            if glow > 0.0 and dist > 0.0:
                t = max(0.0, 1.0 - dist / glow)
                glow_a = t * t * 0.40
            m = a if a >= glow_a else glow_a
            if m <= 0.0:
                return bg
            if m >= 1.0:
                return pix_fill
            return _mix(bg, pix_fill, m)

        dist = _sdf_rounded_rect(px, py, box[0], box[1], box[2], box[3], radius)
        # Glow already falls off smoothly; 9-tap only the pill's own edge
        # so Retina doesn't turn that ring into a broken black hairline.
        if glow > 0.0 and dist > 2.4:
            return one(px, py)
        centre = one(px, py)
        if abs(dist) > 2.4 and not (stroke > 0.0 and outline and abs(dist) < stroke + 2.4):
            return centre
        colors = [
            one(px + dx, py + dy)
            for dx, dy in (
                (-0.33, -0.33), (0.0, -0.33), (0.33, -0.33),
                (-0.33, 0.0), (0.0, 0.0), (0.33, 0.0),
                (-0.33, 0.33), (0.0, 0.33), (0.33, 0.33),
            )
        ]
        return _average_hex(colors)

    if uniform:
        for y in range(height):
            py = y + 0.5
            cells = [sample(x + 0.5, py) for x in range(width)]
            rows.append("{" + " ".join(cells) + "}")
    else:
        mid_x = width / 2.0
        mid_y = height / 2.0
        for y in range(height):
            py = y + 0.5
            row_left = nw if py < mid_y else sw
            row_right = ne if py < mid_y else se
            cells = []
            for x in range(width):
                bg = row_left if (x + 0.5) < mid_x else row_right
                cells.append(sample(x + 0.5, py, bg))
            rows.append("{" + " ".join(cells) + "}")
    img = tk.PhotoImage(width=width, height=height)
    img.put(" ".join(rows))
    if len(_AA_IMAGE_CACHE) >= _AA_IMAGE_CACHE_MAX:
        _AA_IMAGE_CACHE.clear()
    _AA_IMAGE_CACHE[key] = img
    return img


def rounded_rect_image(width: int, height: int, radius: float, fill: str,
                       background: str, outline: str = "", outline_width: float = 1.0,
                       fill_end: str = "", glow: float = 0.0):
    """A PhotoImage of a coverage-antialiased rounded rect.

    Tk's `create_polygon` fill is not antialiased, so on a Retina Mac the
    corner of a 32px button looks stair-stepped. Painting the shape into
    a PhotoImage (blending against `background` per pixel) is how we get
    a smooth edge without extra dependencies, while still using whatever
    fill/outline the current theme asked for.

    `fill_end` paints a left-to-right gradient (Quasar's cyan→violet
    Accent buttons). Empty means a flat fill.

    `glow` is extra pixels of quadratic falloff outside the pill — light
    coming off the fill, not a second stacked button.

    Callers must keep the returned image alive (a widget attribute) so
    Tk doesn't garbage-collect it out from under the canvas.
    """
    stroke = outline_width if outline else 0.0
    return _make_aa_image(
        width, height, radius, fill, background, outline, stroke,
        fill_end=fill_end, glow=glow)


def _keep_aa_image(canvas, img):
    kept = getattr(canvas, "_aa_images", None)
    if kept is None:
        canvas._aa_images = [img]
        return
    kept.append(img)
    if len(kept) > 480:
        canvas._aa_images = kept[-240:]


def _with_transparent_outside(img, background: str):
    """Copy of `img` whose exact-background pixels are see-through.

    Tk widgets are always square; the leftover corner triangles are
    painted in `background`. On the calendar canvas those triangles
    stamp GRID_BG over the today tint. Punching them out lets the grid
    show through so a drag card matches a settled block.
    """
    if not background or not str(background).startswith("#") or len(background) < 7:
        return img
    try:
        r = int(background[1:3], 16)
        g = int(background[3:5], 16)
        b = int(background[5:7], 16)
        out = img.copy()
        w, h = int(out.width()), int(out.height())
        # Only the rounded-rect's outside ring can be the blend color;
        # skipping the interior keeps tall time-block punches cheap.
        band = min(w, h) if min(w, h) <= 40 else 22
        for y in range(h):
            edge_y = y < band or y >= h - band
            for x in range(w):
                if not edge_y and band <= x < w - band:
                    continue
                px = out.get(x, y)
                if isinstance(px, str):
                    parts = px.replace(",", " ").split()
                    got = tuple(int(float(p)) for p in parts[:3])
                else:
                    got = tuple(int(v) for v in px[:3])
                if got == (r, g, b):
                    out.transparency_set(x, y, True)
        return out
    except Exception:
        return img


def _maybe_transparent(img, background: str, transparent_outside: bool):
    if not transparent_outside:
        return img
    return _with_transparent_outside(img, background)


def _corner_patch(corner: str, size: int, radius: float, fill: str,
                  background: str, outline: str, stroke: float):
    far = 4096.0
    if corner == "nw":
        box = (0.5, 0.5, far, far)
    elif corner == "ne":
        box = (size - far, 0.5, size - 0.5, far)
    elif corner == "se":
        box = (size - far, size - far, size - 0.5, size - 0.5)
    else:
        box = (0.5, size - far, far, size - 0.5)
    return _make_aa_image(size, size, radius, fill, background, outline, stroke, box)


def place_rounded_rect(canvas, x1, y1, x2, y2, radius: float = 8, fill: str = "",
                       outline: str = "", width: float = 1, background: str = None,
                       corner_backgrounds=None, full: bool = False,
                       transparent_outside: bool = False, **item_kwargs):
    """Draw a coverage-antialiased rounded rect on `canvas`.

    Small chips (buttons, thumbs, swatches, short time blocks) are a
    single PhotoImage. Large cards use four cached corner patches plus
    rectangles so a sash-drag doesn't re-rasterize the whole panel.

    `corner_backgrounds` is an optional dict of nw/ne/sw/se hex colors used
    when the card floats over more than one surface (the Timer QDM menu
    sits on the timer bar at the top and the timesheet at the bottom).
    Without it, every cut-off corner blends toward a single `background`,
    which reads as a black or white square halo if that color isn't what's
    actually behind the card.

    Returns the item ids created (last id is a stable raise-target).
    Falls back to the polygon `rounded_rect` if PhotoImage isn't usable.
    """
    if x2 < x1:
        x1, x2 = x2, x1
    if y2 < y1:
        y1, y2 = y2, y1
    if background is None:
        try:
            background = canvas.cget("bg") or PANEL_BG
        except Exception:
            background = PANEL_BG

    def _corner_bg(corner: str) -> str:
        if corner_backgrounds:
            color = corner_backgrounds.get(corner)
            if color:
                return color
        return background

    nw, ne, sw, se = _corner_bg("nw"), _corner_bg("ne"), _corner_bg("sw"), _corner_bg("se")
    uniform = nw == ne == sw == se
    paint_bg = nw
    fill = fill or paint_bg
    stroke = float(width) if outline else 0.0
    ox, oy = int(round(x1)), int(round(y1))
    w, h = max(1, int(round(x2 - x1))), max(1, int(round(y2 - y1)))
    radius = max(0.0, min(float(radius), w / 2.0, h / 2.0))
    bgs = None if uniform else (nw, ne, sw, se)
    try:
        # Tall calendar blocks used to trip the "four tiny corner patches"
        # path and look pixelated when you stretched duration. `full=True`
        # keeps one coverage-AA image for the whole shape.
        if full or w * h <= 48000:
            img = _maybe_transparent(
                _make_aa_image(
                    w, h, radius, fill, paint_bg, outline, stroke, backgrounds=bgs),
                paint_bg, transparent_outside)
            _keep_aa_image(canvas, img)
            return [canvas.create_image(ox, oy, image=img, anchor="nw", **item_kwargs)]

        patch = max(2, int(math.ceil(radius)) + 2)
        if patch * 2 >= min(w, h):
            img = _maybe_transparent(
                _make_aa_image(
                    w, h, radius, fill, paint_bg, outline, stroke, backgrounds=bgs),
                paint_bg, transparent_outside)
            _keep_aa_image(canvas, img)
            return [canvas.create_image(ox, oy, image=img, anchor="nw", **item_kwargs)]

        ids = []
        for corner, px, py in (
            ("nw", ox, oy),
            ("ne", ox + w - patch, oy),
            ("sw", ox, oy + h - patch),
            ("se", ox + w - patch, oy + h - patch),
        ):
            img = _corner_patch(
                corner, patch, radius, fill, _corner_bg(corner), outline, stroke)
            _keep_aa_image(canvas, img)
            ids.append(canvas.create_image(px, py, image=img, anchor="nw", **item_kwargs))
        sw = int(round(stroke)) if stroke else 0
        # Straight edges: outer hairline in outline, the rest in fill.
        ids.append(canvas.create_rectangle(
            ox + patch, oy + sw, ox + w - patch, oy + h - sw, fill=fill, outline="", **item_kwargs))
        ids.append(canvas.create_rectangle(
            ox + sw, oy + patch, ox + w - sw, oy + h - patch, fill=fill, outline="", **item_kwargs))
        if sw and outline:
            ids.append(canvas.create_rectangle(
                ox + patch, oy, ox + w - patch, oy + sw, fill=outline, outline="", **item_kwargs))
            ids.append(canvas.create_rectangle(
                ox + patch, oy + h - sw, ox + w - patch, oy + h, fill=outline, outline="", **item_kwargs))
            ids.append(canvas.create_rectangle(
                ox, oy + patch, ox + sw, oy + h - patch, fill=outline, outline="", **item_kwargs))
            ids.append(canvas.create_rectangle(
                ox + w - sw, oy + patch, ox + w, oy + h - patch, fill=outline, outline="", **item_kwargs))
        return ids
    except Exception:
        item = rounded_rect(
            canvas, x1, y1, x2, y2, radius=radius, fill=fill,
            outline=outline, width=width, **item_kwargs)
        return [item]
